In [1]:
import numpy as np
print ("Hello!")

Hello!


Hello this is Lamyaa the creator of this demo.

In [2]:
print("Lamyaa")

Lamyaa




```
# This is formatted as code
```



In [21]:
!pip install numpy
import numpy as np
#define array of np's
my_array=np.array([10,20,30,40],dtype=np.float64)
print(my_array.dtype)

float64


In [22]:
print(my_array)
print(type(my_array))
print(my_array.shape)
print(my_array.dtype)

[10. 20. 30. 40.]
<class 'numpy.ndarray'>
(4,)
float64


In [5]:
my_array[0]=15
print(my_array[0])
print(my_array)

15
[15 20 30 40]


In [7]:
import numpy as np
array2=np.array([[10,20,30,40],[100,200,300,400]])
print(array2)
print(type(array2))
print(array2.shape)
#print(my_array[0:2])
print("new array=",array2[0:1])
print(array2[1:2,1:2])

[[ 10  20  30  40]
 [100 200 300 400]]
<class 'numpy.ndarray'>
(2, 4)
new array= [[10 20 30 40]]
[[200]]


In [19]:
import numpy as np
zero_array=np.zeros([3,3])
print("zeros=",zero_array)
ones_array=np.ones([3,3])
print("ones=",ones_array)
const_array=np.full([3,3],5)
print("const=",const_array)
identity_array=np.eye(3)
print("identity=",identity_array)
random_array=np.random.random([3,3])
print("random=",random_array)
print(random_array.dtype)
print(identity_array.dtype)
print(const_array.dtype)

zeros= [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
ones= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
const= [[5 5 5]
 [5 5 5]
 [5 5 5]]
identity= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random= [[0.63679324 0.03925843 0.91728203]
 [0.49657925 0.88428987 0.23404905]
 [0.85554946 0.72359176 0.79773878]]
float64
float64
int64


In [36]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[10,20,30],[40,50,60]])
print("x=",x,"\n y=",y)
print("x+y=",np.add(x,y))
print("y-x=",np.subtract(y,x))
print("x*y=",np.multiply(x,y))
print("x/y=",np.divide(x,y))
print("sqrt(x)=",np.sqrt(x))

x= [[1 2 3]
 [4 5 6]] 
 y= [[10 20 30]
 [40 50 60]]
x+y= [[11 22 33]
 [44 55 66]]
y-x= [[ 9 18 27]
 [36 45 54]]
x*y= [[ 10  40  90]
 [160 250 360]]
x/y= [[0.1 0.1 0.1]
 [0.1 0.1 0.1]]
sqrt(x)= [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [46]:
#dot product
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])
print("x=",x,"\n y=",y)
v=np.array([9,10])
w=np.array([11,12])
print("dot1=",x.dot(v))
print("dot2=",y.dot(w))
print("dot3=",x.dot(y))
print("x_transpose=",x.T)
vv=np.tile(v,[4,1])
print("vv_broadcasting=",vv)

x= [[1 2]
 [3 4]] 
 y= [[5 6]
 [7 8]]
dot1= [29 67]
dot2= [127 173]
dot3= [[19 22]
 [43 50]]
x_transpose= [[1 3]
 [2 4]]
vv_broadcasting= [[ 9 10]
 [ 9 10]
 [ 9 10]
 [ 9 10]]
